french_mapping = {
    "Aruba": "ABW",
    "Afghanistan": "AFG",
    "Angola": "AGO",
    "Anguilla": "AIA",
    "Îles Åland": "ALA",
    "Albanie": "ALB",
    "Andorre": "AND",
    "Émirats arabes unis": "ARE",
    "Argentine": "ARG",
    "Arménie": "ARM",
    "Samoa américaines": "ASM",
    "Antarctique": "ATA",
    "Terres australes françaises": "ATF",
    "Antigua-et-Barbuda": "ATG",
    "Australie": "AUS",
    "Autriche": "AUT",
    "Azerbaïdjan": "AZE",
    "Burundi": "BDI",
    "Belgique": "BEL",
    "Bénin": "BEN",
    "Bonaire": "BES",
    "Bonaire, Saint-Eustache et Saba": "BES",
    "Burkina Faso": "BFA",
    "Bangladesh": "BGD",
    "Bulgarie": "BGR",
    "Bahreïn": "BHR",
    "Bahamas": "BHS",
    "Bosnie-Herzégovine": "BIH",
    "Saint-Barthélemy": "BLM",
    "Biélorussie": "BLR",
    "Belize": "BLZ",
    "Bermudes": "BMU",
    "Bolivie": "BOL",
    "Brésil": "BRA",
    "Barbade": "BRB",
    "Brunei": "BRN",
    "Bhoutan": "BTN",
    "Île Bouvet": "BVT",
    "Botswana": "BWA",
    "République centrafricaine": "CAF",
    "Canada": "CAN",
    "Îles Cocos": "CCK",
    "Suisse": "CHE",
    "Chili": "CHL",
    "Chine": "CHN",
    "Côte d’Ivoire": "CIV",
    "Cameroun": "CMR",
    "République démocratique du Congo": "COD",
    "Congo": "COG",
    "Îles Cook": "COK",
    "Colombie": "COL",
    "Comores": "COM",
    "Cap-Vert": "CPV",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Curaçao": "CUW",
    "Île Christmas": "CXR",
    "Îles Caïmans": "CYM",
    "Chypre": "CYP",
    "Tchéquie": "CZE",
    "Allemagne": "DEU",
    "Djibouti": "DJI",
    "Dominique": "DMA",
    "Danemark": "DNK",
    "République dominicaine": "DOM",
    "Algérie": "DZA",
    "Équateur": "ECU",
    "Égypte": "EGY",
    "Érythrée": "ERI",
    "Sahara occidental": "ESH",
    "Espagne": "ESP",
    "Estonie": "EST",
    "Éthiopie": "ETH",
    "Finlande": "FIN",
    "Fidji": "FJI",
    "Îles Malouines": "FLK",
    "France": "FRA",
    "Îles Féroé": "FRO",
    "Micronésie": "FSM",
    "Gabon": "GAB",
    "Royaume-Uni": "GBR",
    "Géorgie": "GEO",
    "Guernesey": "GGY",
    "Ghana": "GHA",
    "Gibraltar": "GIB",
    "Guinée": "GIN",
    "Guadeloupe": "GLP",
    "Gambie": "GMB",
    "Guinée-Bissau": "GNB",
    "Guinée équatoriale": "GNQ",
    "Grèce": "GRC",
    "Grenade": "GRD",
    "Groenland": "GRL",
    "Guatemala": "GTM",
    "Guyane française": "GUF",
    "Guam": "GUM",
    "Guyana": "GUY",
    "Hong Kong": "HKG",
    "Îles Heard-et-MacDonald": "HMD",
    "Honduras": "HND",
    "Croatie": "HRV",
    "Haïti": "HTI",
    "Hongrie": "HUN",
    "Indonésie": "IDN",
    "Île de Man": "IMN",
    "Inde": "IND",
    "Territoire britannique de l’océan Indien": "IOT",
    "Irlande": "IRL",
    "Iran": "IRN",
    "Irak": "IRQ",
    "Islande": "ISL",
    "Israël": "ISR",
    "Italie": "ITA",
    "Jamaïque": "JAM",
    "Jersey": "JEY",
    "Jordanie": "JOR",
    "Japon": "JPN",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kirghizistan": "KGZ",
    "Cambodge": "KHM",
    "Kiribati": "KIR",
    "Saint-Christophe-et-Niévès": "KNA",
    "Corée du Sud": "KOR",
    "Koweït": "KWT",
    "Laos": "LAO",
    "Liban": "LBN",
    "Libéria": "LBR",
    "Libye": "LBY",
    "Sainte-Lucie": "LCA",
    "Liechtenstein": "LIE",
    "Sri Lanka": "LKA",
    "Lesotho": "LSO",
    "Lituanie": "LTU",
    "Luxembourg": "LUX",
    "Lettonie": "LVA",
    "Macao": "MAC",
    "Saint-Martin": "MAF",
    "Maroc": "MAR",
    "Monaco": "MCO",
    "Moldavie": "MDA",
    "Madagascar": "MDG",
    "Maldives": "MDV",
    "Mexique": "MEX",
    "Îles Marshall": "MHL",
    "Macédoine du Nord": "MKD",
    "Mali": "MLI",
    "Malte": "MLT",
    "Myanmar": "MMR",
    "Monténégro": "MNE",
    "Mongolie": "MNG",
    "Îles Mariannes du Nord": "MNP",
    "Mozambique": "MOZ",
    "Mauritanie": "MRT",
    "Montserrat": "MSR",
    "Martinique": "MTQ",
    "Maurice": "MUS",
    "Malawi": "MWI",
    "Malaisie": "MYS",
    "Mayotte": "MYT",
    "Namibie": "NAM",
    "Nouvelle-Calédonie": "NCL",
    "Niger": "NER",
    "Île Norfolk": "NFK",
    "Nigeria": "NGA",
    "Nicaragua": "NIC",
    "Niue": "NIU",
    "Pays-Bas": "NLD",
    "Norvège": "NOR",
    "Népal": "NPL",
    "Nauru": "NRU",
    "Nouvelle-Zélande": "NZL",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Pitcairn": "PCN",
    "Pérou": "PER",
    "Philippines": "PHL",
    "Palaos": "PLW",
    "Papouasie-Nouvelle-Guinée": "PNG",
    "Pologne": "POL",
    "Porto Rico": "PRI",
    "Corée du Nord": "PRK",
    "Portugal": "PRT",
    "Paraguay": "PRY",
    "Palestine": "PSE",
    "Polynésie française": "PYF",
    "Qatar": "QAT",
    "La Réunion": "REU",
    "Roumanie": "ROU",
    "Russie": "RUS",
    "Rwanda": "RWA",
    "Arabie saoudite": "SAU",
    "Soudan": "SDN",
    "Sénégal": "SEN",
    "Singapour": "SGP",
    "Géorgie du Sud-et-les Îles Sandwich du Sud": "SGS",
    "Sainte-Hélène": "SHN",
    "Svalbard et Jan Mayen": "SJM",
    "Îles Salomon": "SLB",
    "Sierra Leone": "SLE",
    "Salvador": "SLV",
    "Saint-Marin": "SMR",
    "Somalie": "SOM",
    "Saint-Pierre-et-Miquelon": "SPM",
    "Serbie": "SRB",
    "Soudan du Sud": "SSD",
    "Sao Tomé-et-Principe": "STP",
    "Suriname": "SUR",
    "Slovaquie": "SVK",
    "Slovénie": "SVN",
    "Suède": "SWE",
    "Eswatini": "SWZ",
    "Saint-Martin (partie néerlandaise)": "SXM",
    "Seychelles": "SYC",
    "Syrie": "SYR",
    "Îles Turques-et-Caïques": "TCA",
    "Tchad": "TCD",
    "Togo": "TGO",
    "Thaïlande": "THA",
    "Tadjikistan": "TJK",
    "Tokelau": "TKL",
    "Turkménistan": "TKM",
    "Timor oriental": "TLS",
    "Tonga": "TON",
    "Trinité-et-Tobago": "TTO",
    "Tunisie": "TUN",
    "Turquie": "TUR",
    "Tuvalu": "TUV",
    "Taïwan": "TWN",
    "Tanzanie": "TZA",
    "Ouganda": "UGA",
    "Ukraine": "UKR",
    "Îles mineures éloignées des États-Unis": "UMI",
    "Uruguay": "URY",
    "États-Unis": "USA",
    "Ouzbékistan": "UZB",
    "Saint-Siège": "VAT",
    "Saint-Vincent-et-les-Grenadines": "VCT",
    "Venezuela": "VEN",
    "Îles Vierges britanniques": "VGB",
    "Îles Vierges des États-Unis": "VIR",
    "Viêt Nam": "VNM",
    "Vanuatu": "VUT",
    "Wallis-et-Futuna": "WLF",
    "Samoa": "WSM",
    "Yémen": "YEM",
    "Afrique du Sud": "ZAF",
    "Zambie": "ZMB",
    "Zimbabwe": "ZWE",
}
