"""
Utility functions for the laser.init package.
"""

import rapidfuzz

__iso_codes__ = {
    "ABW",
    "AFG",
    "AGO",
    "AIA",
    "ALA",
    "ALB",
    "AND",
    "ARE",
    "ARG",
    "ARM",
    "ASM",
    "ATA",
    "ATF",
    "ATG",
    "AUS",
    "AUT",
    "AZE",
    "BDI",
    "BEL",
    "BEN",
    "BES",
    "BFA",
    "BGD",
    "BGR",
    "BHR",
    "BHS",
    "BIH",
    "BLM",
    "BLR",
    "BLZ",
    "BMU",
    "BOL",
    "BRA",
    "BRB",
    "BRN",
    "BTN",
    "BVT",
    "BWA",
    "CAF",
    "CAN",
    "CCK",
    "CHE",
    "CHL",
    "CHN",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COK",
    "COL",
    "COM",
    "CPV",
    "CRI",
    "CUB",
    "CUW",
    "CXR",
    "CYM",
    "CYP",
    "CZE",
    "DEU",
    "DJI",
    "DMA",
    "DNK",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ERI",
    "ESH",
    "ESP",
    "EST",
    "ETH",
    "FIN",
    "FJI",
    "FLK",
    "FRA",
    "FRO",
    "FSM",
    "GAB",
    "GBR",
    "GEO",
    "GGY",
    "GHA",
    "GIB",
    "GIN",
    "GLP",
    "GMB",
    "GNB",
    "GNQ",
    "GRC",
    "GRD",
    "GRL",
    "GTM",
    "GUF",
    "GUM",
    "GUY",
    "HKG",
    "HMD",
    "HND",
    "HRV",
    "HTI",
    "HUN",
    "IDN",
    "IMN",
    "IND",
    "IOT",
    "IRL",
    "IRN",
    "IRQ",
    "ISL",
    "ISR",
    "ITA",
    "JAM",
    "JEY",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KGZ",
    "KHM",
    "KIR",
    "KNA",
    "KOR",
    "KWT",
    "LAO",
    "LBN",
    "LBR",
    "LBY",
    "LCA",
    "LIE",
    "LKA",
    "LSO",
    "LTU",
    "LUX",
    "LVA",
    "MAC",
    "MAF",
    "MAR",
    "MCO",
    "MDA",
    "MDG",
    "MDV",
    "MEX",
    "MHL",
    "MKD",
    "MLI",
    "MLT",
    "MMR",
    "MNE",
    "MNG",
    "MNP",
    "MOZ",
    "MRT",
    "MSR",
    "MTQ",
    "MUS",
    "MWI",
    "MYS",
    "MYT",
    "NAM",
    "NCL",
    "NER",
    "NFK",
    "NGA",
    "NIC",
    "NIU",
    "NLD",
    "NOR",
    "NPL",
    "NRU",
    "NZL",
    "OMN",
    "PAK",
    "PAN",
    "PCN",
    "PER",
    "PHL",
    "PLW",
    "PNG",
    "POL",
    "PRI",
    "PRK",
    "PRT",
    "PRY",
    "PSE",
    "PYF",
    "QAT",
    "REU",
    "ROU",
    "RUS",
    "RWA",
    "SAU",
    "SDN",
    "SEN",
    "SGP",
    "SGS",
    "SHN",
    "SJM",
    "SLB",
    "SLE",
    "SLV",
    "SMR",
    "SOM",
    "SPM",
    "SRB",
    "SSD",
    "STP",
    "SUR",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "SXM",
    "SYC",
    "SYR",
    "TCA",
    "TCD",
    "TGO",
    "THA",
    "TJK",
    "TKL",
    "TKM",
    "TLS",
    "TON",
    "TTO",
    "TUN",
    "TUR",
    "TUV",
    "TWN",
    "TZA",
    "UGA",
    "UKR",
    "UMI",
    "URY",
    "USA",
    "UZB",
    "VAT",
    "VCT",
    "VEN",
    "VGB",
    "VIR",
    "VNM",
    "VUT",
    "WLF",
    "WSM",
    "YEM",
    "ZAF",
    "ZMB",
    "ZWE",
}

__name_mapping__ = {
    "Aruba": "ABW",
    "Afghanistan": "AFG",
    "Angola": "AGO",
    "Anguilla": "AIA",
    "Åland Islands": "ALA",
    "Albania": "ALB",
    "Andorra": "AND",
    "United Arab Emirates": "ARE",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "American Samoa": "ASM",
    "Antarctica": "ATA",
    "French Southern Territories": "ATF",
    "Antigua and Barbuda": "ATG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Burundi": "BDI",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Bonaire": "BES",
    "Bonaire, Sint Eustatius and Saba": "BES",
    "Burkina Faso": "BFA",
    "Bangladesh": "BGD",
    "Bulgaria": "BGR",
    "Bahrain": "BHR",
    "Bahamas": "BHS",
    "Bosnia": "BIH",
    "Herzegovina": "BIH",
    "Bosnia and Herzegovina": "BIH",
    "Saint Barthelemy": "BLM",
    "Saint Barthélemy": "BLM",
    "Belarus": "BLR",
    "Belize": "BLZ",
    "Bermuda": "BMU",
    "Bolivia": "BOL",
    "Bolivia, Plurinational State of": "BOL",
    "Brazil": "BRA",
    "Barbados": "BRB",
    "Brunei": "BRN",
    "Brunei Darussalam": "BRN",
    "Bhutan": "BTN",
    "Bouvet Island": "BVT",
    "Botswana": "BWA",
    "Central African Republic": "CAF",
    "Canada": "CAN",
    "Cocos Islands": "CCK",
    "Cocos (Keeling) Islands": "CCK",
    "Switzerland": "CHE",
    "Chile": "CHL",
    "China": "CHN",
    "Côte d'Ivoire": "CIV",
    "Cameroon": "CMR",
    "DRC": "COD",
    "Congo, Democratic Republic of the": "COD",
    "Congo": "COG",
    "Cook Islands": "COK",
    "Colombia": "COL",
    "Comoros": "COM",
    "Cabo Verde": "CPV",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Curacao": "CUW",
    "Curaçao": "CUW",
    "Christmas Island": "CXR",
    "Cayman Islands": "CYM",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Germany": "DEU",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Denmark": "DNK",
    "Dominican Republic": "DOM",
    "Algeria": "DZA",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "Eritrea": "ERI",
    "Western Sahara": "ESH",
    "Spain": "ESP",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Finland": "FIN",
    "Fiji": "FJI",
    "Falkland Islands": "FLK",
    "Falkland Islands (Malvinas)": "FLK",
    "France": "FRA",
    "Faroe Islands": "FRO",
    "Micronesia": "FSM",
    "Micronesia, Federated States of": "FSM",
    "Gabon": "GAB",
    "Great Britain": "GBR",
    "United Kingdom": "GBR",
    "United Kingdom of Great Britain and Northern Ireland": "GBR",
    "Georgia": "GEO",
    "Guernsey": "GGY",
    "Ghana": "GHA",
    "Gibraltar": "GIB",
    "Guinea": "GIN",
    "Guadeloupe": "GLP",
    "Gambia": "GMB",
    "Guinea Bissau": "GNB",
    "Guinea-Bissau": "GNB",
    "Equatorial Guinea": "GNQ",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Greenland": "GRL",
    "Guatemala": "GTM",
    "French Guiana": "GUF",
    "Guam": "GUM",
    "Guyana": "GUY",
    "Hong Kong": "HKG",
    "McDonald Islands": "HMD",
    "Heard Island": "HMD",
    "Heard Island and McDonald Islands": "HMD",
    "Honduras": "HND",
    "Croatia": "HRV",
    "Haiti": "HTI",
    "Hungary": "HUN",
    "Indonesia": "IDN",
    "Isle of Man": "IMN",
    "India": "IND",
    "British Indian Ocean Territory": "IOT",
    "Ireland": "IRL",
    "Iran": "IRN",
    "Iran, Islamic Republic of": "IRN",
    "Islamic Republic of Iran": "IRN",
    "Iraq": "IRQ",
    "Iceland": "ISL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Jersey": "JEY",
    "Jordan": "JOR",
    "Japan": "JPN",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kyrgyzstan": "KGZ",
    "Cambodia": "KHM",
    "Kiribati": "KIR",
    "Saint Kitts": "KNA",
    "Saint Kitts and Nevis": "KNA",
    "Korea, Republic of": "KOR",
    "Republic of Korea": "KOR",
    "Kuwait": "KWT",
    "Laos": "LAO",
    "Lao People's Democratic Republic": "LAO",
    "Lebanon": "LBN",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Saint Lucia": "LCA",
    "Liechtenstein": "LIE",
    "Sri Lanka": "LKA",
    "Lesotho": "LSO",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Latvia": "LVA",
    "Macao": "MAC",
    "Saint Martin (French part)": "MAF",
    "Morocco": "MAR",
    "Monaco": "MCO",
    "Moldova": "MDA",
    "Moldova, Republic of": "MDA",
    "Republic of Moldova": "MDA",
    "Madagascar": "MDG",
    "Maldives": "MDV",
    "Mexico": "MEX",
    "Marshall Islands": "MHL",
    "North Macedonia": "MKD",
    "Mali": "MLI",
    "Malta": "MLT",
    "Myanmar": "MMR",
    "Montenegro": "MNE",
    "Mongolia": "MNG",
    "Northern Mariana Islands": "MNP",
    "Mozambique": "MOZ",
    "Mauritania": "MRT",
    "Montserrat": "MSR",
    "Martinique": "MTQ",
    "Mauritius": "MUS",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    "Mayotte": "MYT",
    "Namibia": "NAM",
    "New Caledonia": "NCL",
    "Niger": "NER",
    "Norfolk Island": "NFK",
    "Nigeria": "NGA",
    "Nicaragua": "NIC",
    "Niue": "NIU",
    "Netherlands": "NLD",
    "Kingdom of the Netherlands": "NLD",
    "Netherlands, Kingdom of the": "NLD",
    "Norway": "NOR",
    "Nepal": "NPL",
    "Nauru": "NRU",
    "New Zealand": "NZL",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Pitcairn": "PCN",
    "Peru": "PER",
    "Philippines": "PHL",
    "Palau": "PLW",
    "Papua New Guinea": "PNG",
    "Poland": "POL",
    "Puerto Rico": "PRI",
    "Korea, Democratic People's Republic of": "PRK",
    "Korea": "PRK",
    "Democratic People's Republic of Korea": "PRK",
    "Portugal": "PRT",
    "Paraguay": "PRY",
    "Palestine": "PSE",
    "Palestine, State of": "PSE",
    "State of Palestine": "PSE",
    "French Polynesia": "PYF",
    "Qatar": "QAT",
    "Reunion": "REU",
    "Réunion": "REU",
    "Romania": "ROU",
    "Russian Federation": "RUS",
    "Rwanda": "RWA",
    "Saudi Arabia": "SAU",
    "Sudan": "SDN",
    "Senegal": "SEN",
    "Singapore": "SGP",
    "South Georgia and the South Sandwich Islands": "SGS",
    "Saint Helena": "SHN",
    "Saint Helena, Ascension and Tristan da Cunha": "SHN",
    "Svalbard": "SJM",
    "Svalbard and Jan Mayen": "SJM",
    "Solomon Islands": "SLB",
    "Sierra Leone": "SLE",
    "El Salvador": "SLV",
    "San Marino": "SMR",
    "Somalia": "SOM",
    "Saint Pierre": "SPM",
    "Saint Pierre and Miquelon": "SPM",
    "Serbia": "SRB",
    "South Sudan": "SSD",
    "Sao Tome and Principe": "STP",
    "Sao Tome": "STP",
    "Suriname": "SUR",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Sweden": "SWE",
    "Eswatini": "SWZ",
    "Sint Maarten (Dutch part)": "SXM",
    "Seychelles": "SYC",
    "Syria": "SYR",
    "Syrian Arab Republic": "SYR",
    "Turks and Caicos": "TCA",
    "Turks and Caicos Islands": "TCA",
    "Chad": "TCD",
    "Togo": "TGO",
    "Thailand": "THA",
    "Tajikistan": "TJK",
    "Tokelau": "TKL",
    "Turkmenistan": "TKM",
    "Timor-Leste": "TLS",
    "Tonga": "TON",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Türkiye": "TUR",
    "Tuvalu": "TUV",
    "Taiwan": "TWN",
    "Taiwan, Province of China": "TWN",
    "Tanzania": "TZA",
    "Tanzania, United Republic of": "TZA",
    "United Republic of Tanzania": "TZA",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United States Minor Outlying Islands": "UMI",
    "Uruguay": "URY",
    "United States of America": "USA",
    "Uzbekistan": "UZB",
    "Holy See": "VAT",
    "Saint Vincent and the Grenadines": "VCT",
    "Venezuela, Bolivarian Republic of": "VEN",
    "Virgin Islands (British)": "VGB",
    "Virgin Islands (US)": "VIR",
    "Virgin Islands (U.S.)": "VIR",
    "Viet Nam": "VNM",
    "Vanuatu": "VUT",
    "Wallis and Futuna": "WLF",
    "Samoa": "WSM",
    "Yemen": "YEM",
    "South Africa": "ZAF",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
}


def iso_from_country_string(country_string):
    """
    Convert a country name to its ISO 3166-1 alpha-3 code.
    """
    if country_string in __iso_codes__:
        return country_string
    elif country_string in __name_mapping__:
        return __name_mapping__[country_string]

    # Try fuzzy matching
    # If it's a close match to a country name in __name_mapping__, return the corresponding ISO code
    best_match = rapidfuzz.process.extractOne(country_string, __name_mapping__.keys())
    if best_match:
        if best_match[1] > 80:
            # If the best match has a score greater than 80, consider it a match and return the corresponding ISO code
            return __name_mapping__[best_match[0]]
        else:
            print(f"Warning: '{country_string}' is not a good match to any known country name.")
            # Provide some suggestions for the user to consider
            suggestions = rapidfuzz.process.extract(
                country_string, __name_mapping__.keys(), limit=5
            )
            print("Did you mean:")
            for suggestion in suggestions:
                print(f"  - {suggestion[0]} (score: {suggestion[1]})")
            # return None
    else:
        print(f"Warning: '{country_string}' is not a good match to any known country name.")
        # return None

    return None
